2019-03-06 10:05:35 [   DEBUG] <module 'data.case.apitalk' from 'E:\\code\\apitest\\data\\case\\apitalk.py'> (dynamic_execution.py:12)
2019-03-06 10:05:35 [   DEBUG] imported_functions_dict:{'api_v1_Account_Login_POST': <function api_v1_Account_Login_POST at 0x0000024E14073378>, 'api_v1_Account_LoginOff_GET': <function api_v1_Account_LoginOff_GET at 0x0000024E14073488>} (dynamic_execution.py:14)
2019-03-06 10:05:35 [   DEBUG] ('api_v1_Account_Login_POST', '$UserName, $Password') (parser.py:30)
2019-03-06 10:05:35 [   DEBUG] function_meta:{'args': ['$UserName', '$Password'], 'kwargs': {}, 'func_name': 'api_v1_Account_Login_POST'} (dynamic_execution.py:60)
2019-03-06 10:05:35 [   DEBUG] ('api_v1_Account_LoginOff_GET', '') (parser.py:30)
2019-03-06 10:05:35 [   DEBUG] function_meta:{'args': [], 'kwargs': {}, 'func_name': 'api_v1_Account_LoginOff_GET'} (dynamic_execution.py:60)
2019-03-06 10:05:35 [   DEBUG] <module 'data.case.apitalk' from 'E:\\code\\apitest\\data\\case\\apitalk.py'> (dynamic_execution.py:12)
2019-03-06 10:05:35 [   DEBUG] imported_functions_dict:{'api_v1_Account_Login_POST': <function api_v1_Account_Login_POST at 0x0000024E14073378>, 'api_v1_Account_LoginOff_GET': <function api_v1_Account_LoginOff_GET at 0x0000024E14073488>} (dynamic_execution.py:14)
2019-03-06 10:05:35 [   DEBUG] ('api_v1_Account_Login_POST', '$UserName, $Password') (parser.py:30)
2019-03-06 10:05:35 [   DEBUG] function_meta:{'args': ['$UserName', '$Password'], 'kwargs': {}, 'func_name': 'api_v1_Account_Login_POST'} (dynamic_execution.py:60)
2019-03-06 10:05:35 [   DEBUG] ('api_v1_Account_LoginOff_GET', '') (parser.py:30)
2019-03-06 10:05:35 [   DEBUG] function_meta:{'args': [], 'kwargs': {}, 'func_name': 'api_v1_Account_LoginOff_GET'} (dynamic_execution.py:60)
2019-03-06 10:05:35 [   DEBUG] <module 'data.case.debugtalk' from 'E:\\code\\apitest\\data\\case\\debugtalk.py'> (dynamic_execution.py:12)
2019-03-06 10:05:35 [   DEBUG] imported_functions_dict:{'gen_random_string': <function gen_random_string at 0x0000024E140C0400>, 'gen_md5': <function gen_md5 at 0x0000024E140C0488>} (dynamic_execution.py:14)
2019-03-06 10:05:35 [   DEBUG] ('gen_random_string', '5') (parser.py:30)
2019-03-06 10:05:35 [   DEBUG] function_meta:{'args': [5], 'kwargs': {}, 'func_name': 'gen_random_string'} (dynamic_execution.py:60)
2019-03-06 10:05:35 [   DEBUG] ('gen_md5', '$TOKEN, $json, $random') (parser.py:30)
2019-03-06 10:05:35 [   DEBUG] function_meta:{'args': ['$TOKEN', '$json', '$random'], 'kwargs': {}, 'func_name': 'gen_md5'} (dynamic_execution.py:60)
2019-03-06 10:05:35 [   DEBUG] ('gen_random_string', '5') (parser.py:30)
2019-03-06 10:05:35 [   DEBUG] function_meta:{'args': [5], 'kwargs': {}, 'func_name': 'gen_random_string'} (dynamic_execution.py:60)
2019-03-06 10:05:35 [   DEBUG] ('gen_md5', '$TOKEN, $json, $random') (parser.py:30)
2019-03-06 10:05:35 [   DEBUG] function_meta:{'args': ['$TOKEN', '$json', '$random'], 'kwargs': {}, 'func_name': 'gen_md5'} (dynamic_execution.py:60)
2019-03-06 10:05:35 [   DEBUG] get_eval_value:{'name': 'create user which does not exist', 'import_module_functions': ['data.case.debugtalk'], 'variables': [{'TOKEN': 'debugtalk'}, {'json': {'name': 'user', 'password': '123456'}}, {'random': 'Heus7'}, {'authorization': 'd16262807557a85ab435bd6f4e2bb7a0'}], 'request': {'url': 'http://127.0.0.1:5000/api/users/1000', 'method': 'POST', 'headers': {'Content-Type': 'application/json', 'random': 'yOWzZ', 'authorization': 'fd076b2eca2f5e67f823952f0b5ddf11'}, 'json': {'name': 'user', 'password': '123456'}}, 'response': {'status_code': 201, 'success': 'true,', 'msg': 'user created successfully.'}} (test_runner.py:15)
2019-03-06 10:05:35 [    INFO] 执行用例create user which does not exist (test_runner.py:16)
2019-03-06 10:05:35 [    INFO] 请求数据:{'headers': {'Content-Type': 'application/json', 'random': '${gen_random_string(5)}', 'authorization': '${gen_md5($TOKEN, $json, $random)}'}, 'json': {'name': 'user', 'password': '123456'}} (test_runner.py:23)
2019-03-06 10:05:35 [   DEBUG] Starting new HTTP connection (1): 127.0.0.1:5000 (connectionpool.py:205)
2019-03-06 10:05:35 [   DEBUG] http://127.0.0.1:5000 "POST /api/users/1000 HTTP/1.1" 401 56 (connectionpool.py:393)
2019-03-06 10:05:35 [    INFO] 响应数据;{"success": false, "msg": "device_sn or token is null."} (test_runner.py:25)
2019-03-06 10:05:35 [    INFO] 预期响应与实际响应的差异:{'status_code': {'实际响应': 401, '预期响应': 201}, 'success': {'实际响应': None, '预期响应': 'true,'}, 'msg': {'实际响应': None, '预期响应': 'user created successfully.'}} (test_runner.py:27)
2019-03-06 10:05:35 [    INFO] 执行用例Login (test_runner.py:35)
2019-03-06 10:05:35 [    INFO] 请求数据:{'headers': {'Accept': 'application/json', 'User-Agent': 'iOS/10.3', 'Content-Type': 'application/json'}, 'json': {'UserName': 'test001', 'Pwd': 123456, 'VerCode': ''}} (test_runner.py:43)
2019-03-06 10:05:35 [   DEBUG] Starting new HTTP connection (1): 127.0.0.1:5000 (connectionpool.py:205)
2019-03-06 10:05:35 [   DEBUG] http://127.0.0.1:5000 "POST /api/v1/Account/Login HTTP/1.1" 404 233 (connectionpool.py:393)
2019-03-06 10:05:35 [    INFO] 响应数据;<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
 (test_runner.py:45)
2019-03-06 10:05:35 [    INFO] 预期响应与实际响应的差异:{'status_code': {'实际响应': 404, '预期响应': 200}, 'content.IsSuccess': {'实际响应': None, '预期响应': 'True,'}, 'content.Code': {'实际响应': None, '预期响应': 200}} (test_runner.py:48)
2019-03-06 10:05:35 [    INFO] 执行用例Logoff (test_runner.py:35)
2019-03-06 10:05:35 [    INFO] 请求数据:{'headers': {'Accept': 'application/json', 'User-Agent': 'iOS/10.3', 'Content-Type': 'application/json'}} (test_runner.py:43)
2019-03-06 10:05:35 [   DEBUG] Starting new HTTP connection (1): 127.0.0.1:5000 (connectionpool.py:205)
2019-03-06 10:05:35 [   DEBUG] http://127.0.0.1:5000 "GET /api/v1/Account/LoginOff HTTP/1.1" 404 233 (connectionpool.py:393)
2019-03-06 10:05:35 [    INFO] 响应数据;<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
 (test_runner.py:45)
2019-03-06 10:05:35 [    INFO] 预期响应与实际响应的差异:{'status_code': {'实际响应': 404, '预期响应': 200}, 'content.IsSuccess': {'实际响应': None, '预期响应': 'True,'}, 'content.Code': {'实际响应': None, '预期响应': 200}} (test_runner.py:48)
